<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>KEYI</AssemblyName>
    <RootNamespace>KEYI.Windows</RootNamespace>
    <Version>1.1.5</Version>
    <Company>KEYI</Company>
    <Product>KEYI 可译</Product>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\KEYI.Core\KEYI.Core.csproj" />
  </ItemGroup>
</Project>
